Sat Sep  9 13:26:49 CEST 2017

diff --git a/@extra/.pkgs/debian/postinst b/@extra/.pkgs/debian/postinst
--- a/@extra/.pkgs/debian/postinst
+++ b/@extra/.pkgs/debian/postinst
@@ -22,12 +22,21 @@ if [ -d ${_tmpdir} ]; then
 fi
 #dirs!
 mkdir -p ${_tmpdir}/usr/share/themes
-#downloading and extracting
+#downloading
 cd /tmp
-curl -L https://codeload.github.com/sixsixfive/0nyX/zip/master > /tmp/0nyX.zip
+if type wget >/dev/null 2>&1; then
+	wget -O /tmp/0nyX.zip https://codeload.github.com/sixsixfive/0nyX/zip/master
+elif type curl >/dev/null 2>&1; then
+	curl -o /tmp/0nyX.zip https://codeload.github.com/sixsixfive/0nyX/zip/master
+fi
 if [ -f ${_tmpdir}/../0nyX.zip ]; then
-	unzip ${_tmpdir}/../0nyX.zip -d ${_tmpdir}/usr/share/themes
-	mv ${_tmpdir}/usr/share/themes/0nyX-master ${_tmpdir}/usr/share/themes/0nyX
+	if unzip -Z ${_tmpdir}/../0nyX.zip > /dev/null; then
+		unzip ${_tmpdir}/../0nyX.zip -d ${_tmpdir}/usr/share/themes
+		mv ${_tmpdir}/usr/share/themes/0nyX-master ${_tmpdir}/usr/share/themes/0nyX
+	else
+		printf "archive is corrupt - aborting!\n"
+		exit 1
+	fi
 fi
 ###link all themes
 if [ -d ${_tmpdir}/usr/share/themes/0nyX ]; then
@@ -38,16 +47,11 @@ if [ -d ${_tmpdir}/usr/share/themes/0nyX ]; then
 		ln -sf ../../themes/0nyX/@extra/appthemes/icewm/$_f ${_tmpdir}/usr/share/icewm/themes/$_f
 	done
 #plank theme
-	#mkdir -p ${_tmpdir}/usr/share/plank/themes
-	#ln -sf ../../themes/0nyX/@extra/plank/0nyX ${_tmpdir}/usr/share/plank/themes/0nyX
 	mkdir -p ${_tmpdir}/usr/share/plank/themes
 	for _f in $(find ${_tmpdir}/usr/share/themes/0nyX/@extra/appthemes/plank/ -mindepth 1 -type d|sed 's\^.*/\\g'); do
 		ln -sf ../../themes/0nyX/@extra/appthemes/plank/$_f ${_tmpdir}/usr/share/plank/themes/$_f
 	done
 #onboard
-	#mkdir -p ${_tmpdir}/usr/share/onboard/themes
-	#ln -sf ../../themes/0nyX/@extra/onboard/0nyX/0nyX.colors ${_tmpdir}/usr/share/onboard/themes
-	#ln -sf ../../themes/0nyX/@extra/onboard/0nyX/0nyX.theme ${_tmpdir}/usr/share/onboard/themes
 	mkdir -p ${_tmpdir}/usr/share/onboard/themes
 	for _f in $(find ${_tmpdir}/usr/share/themes/0nyX/@extra/appthemes/onboard -type f|sed 's\^.*/\\g'); do
 		ln -sf ../../themes/0nyX/@extra/appthemes/onboard/$_f ${_tmpdir}/usr/share/onboard/themes/$_f
@@ -55,7 +59,6 @@ if [ -d ${_tmpdir}/usr/share/themes/0nyX ]; then
 #qt5ct
 	mkdir -p ${_tmpdir}/usr/share/qt5ct/colors ${_tmpdir}/usr/share/qt5ct/qss
 	ln -sf ../../themes/0nyX/@extra/appthemes/qt5ct/0nyX/colors/0nyX.conf ${_tmpdir}/usr/share/qt5ct/colors
-	ln -sf ../../themes/0nyX/@extra/appthemes/qt5ct/0nyX/qss/0nyX_QGtkStyle.qss ${_tmpdir}/usr/share/qt5ct/qss
 	ln -sf ../../themes/0nyX/@extra/appthemes/qt5ct/0nyX/qss/0nyX_QFusionStyle.qss ${_tmpdir}/usr/share/qt5ct/qss
 #albert(app does not support symlinks!)
 	mkdir -p ${_tmpdir}/usr/share/albert/themes
@@ -77,15 +80,17 @@ if [ -d ${_tmpdir}/usr/share/themes/0nyX ]; then
 #	printf "export GTK_OVERLAY_SCROLLING=0\nexport LIBOVERLAY_SCROLLBAR=0\n" > ${_tmpdir}/etc/X11/Xsession.d/98_0nyX
 #xsession.d was a good idea however it wont work with root apps like synaptic so use /etc/environment instead
 	printf '\n#0nyX\nGTK_OVERLAY_SCROLLING=0\n#0nyX\nLIBOVERLAY_SCROLLBAR=0'>> /etc/environment
-#######Debian-only!
-#chromium scrollbars
-	mkdir -p ${_tmpdir}/etc/chromium.d
-	cat <<\EOF > ${_tmpdir}/etc/chromium.d/0nyX
-export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --load-extension=/usr/share/themes/0nyX/@extra/appthemes/Chromium_unpackedextension/0nyX"
-EOF
 #create a file list!
 	find ${_tmpdir} > ${_tmpdir}/usr/share/themes/0nyX/files
 	sed -i 's|^/tmp/0nyX.tmp||g' ${_tmpdir}/usr/share/themes/0nyX/files
 	chmod -R 755 ${_tmpdir}
 	cp -R ${_tmpdir}/* /
+##################
+###Debian-only!###
+##################
+#chromium scrollbars
+	mkdir -p ${_tmpdir}/etc/chromium.d
+	cat <<\EOF > ${_tmpdir}/etc/chromium.d/0nyX
+export CHROMIUM_FLAGS="$CHROMIUM_FLAGS --load-extension=/usr/share/themes/0nyX/@extra/appthemes/Chromium_unpackedextension/0nyX"
+EOF
 fi
